version: '3'

services:
  database:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123123"
    volumes:
      - $PWD/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - '3308:3306'


  iwara:
    image: iwara
    container_name: iwara
    volumes:
      - $PWD:/go/src/iwara
    environment:
      GOPROXY: "https://goproxy.io,direct"
      GO111MODULE: "on"
      GOPATH: "/go"
    ports:
      - "3939:3939"
      - "1087:1087"
    command: go build main.go
    depends_on:
      - database

  debug:
    image: iwara_debug
    container_name: debug
    volumes:
      - $PWD:/go/src/iwara
    environment:
      GOPROXY: "https://goproxy.io,direct"
      GO111MODULE: "on"
      GOPATH: "/go"
    ports:
      - "40000:40000"
    command: /dlv --headless --listen=:40000 --api-version=2 exec /server
    depends_on:
      - database

