version: '3'

services:
  iwara:
    image: iwara
    volumes:
      - $PWD:/go/src/iwara
    environment:
      GOPROXY: "https://goproxy.io,direct"
      GO111MODULE: "on"
      GOPATH: "/go"
    ports:
      - "3939:3939"
    depends_on:
      - database

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123123"
    volumes:
      - $PWD/data.sql:/docker-entrypoint-initdb.d/data.sql
    ports:
      - '3308:3306'
